
function onCreate()
-- dejar si o si  bar, black, black2, blackbar, blackbar2, blackbar3, white, whitescreen (el resto hay q ponerlos en cada stage)
	precacheImage('ahhh');
	precacheImage('bar');
	
	precacheImage('bbsign');
	precacheImage('bbsign2');
	precacheImage('black');
	precacheImage('black2');
	precacheImage('blackbar');
	precacheImage('blackbar2');
	precacheImage('blackbar3');
	precacheImage('cbon');
	precacheImage('cchic');
	precacheImage('cfred');
	precacheImage('challengbonnie');
	precacheImage('challengchic');
	precacheImage('challengchicnotice');
	precacheImage('challengefrednotice');
	precacheImage('chicjump');

	precacheImage('cmang');
	precacheImage('cmanglefall');
	precacheImage('gamerstage');
	precacheImage('gamerstage2');
	precacheImage('gamerstage3');
	precacheImage('gamerstage4');
	precacheImage('gfj');
	precacheImage('golden');
	precacheImage('jj');
	precacheImage('jjhead');
	---------------------------------
	precacheImage('leftnotes');
	precacheImage('rightnotes');
	--------------------------------------
	precacheImage('manglej');
	precacheImage('manglestage2');
	precacheImage('mrhugsjump');
	precacheImage('notresponding');
	precacheImage('pupj1');
	precacheImage('pupj2');
	precacheImage('pupj3');
	precacheImage('pupstage2');

	
	precacheImage('sbstage2');

	precacheImage('shadowstageglitch');
	precacheImage('sparkleeffect');
	precacheImage('stars');
	precacheImage('static');
	precacheImage('static2');
	precacheImage('staticpurp');
	precacheImage('rain');
	-----------------------------------------------------
	precacheImage('tbpossesed');
	precacheImage('tbstage2');
	precacheImage('tcstage2');
	precacheImage('tfstage5');
	precacheImage('tfstage6');
	precacheImage('theballoon');
	precacheImage('theballoon2');
	precacheImage('theballoon3');
	precacheImage('theballoon4');
	precacheImage('tmangstage20');
	precacheImage('wbj');
	precacheImage('wbstage4');
	precacheImage('wcstage2');
	precacheImage('wcstage3');
	precacheImage('wfj');
	precacheImage('wfj2');
	precacheImage('wfoxystage2');
	precacheImage('wfoxystage3');
	precacheImage('wfstage2');
	precacheImage('wfstage3');
	precacheImage('wfstage5');
	precacheImage('white');
	precacheImage('whitescreen');
	precacheImage('yofbstage');
	precacheImage('yofcstage');
	precacheImage('yoffoxstage');
	precacheImage('yoffreddystage');
	precacheImage('yoffstage');
	precacheImage('characters/gtfreddyrage');
	precacheImage('characters/golden2');
	precacheImage('characters/bf7');
	precacheImage('characters/bf1');
	precacheImage('characters/bf2');
	precacheImage('characters/bf3');
	precacheImage('characters/bf4');
	precacheImage('characters/bf5');
	precacheImage('characters/bf6');
	precacheImage('characters/bf8');

	precacheImage('characters/bf10');
	precacheImage('characters/bf11');
	precacheImage('characters/bf12');
	precacheImage('characters/bf13');
	precacheImage('characters/bf14');
	precacheImage('characters/bf15');
	precacheImage('characters/bf16');
	precacheImage('characters/gf2');
	precacheImage('characters/gf3');
	precacheImage('characters/gf4');
	precacheImage('characters/gf5');
	precacheImage('characters/bfpuppet2');
	precacheImage('characters/mangle3');
	precacheImage('characters/sbonnie');
	precacheImage('tbpossesed');
	precacheImage('wfoxyrun');
	precacheImage('bfrun');
	precacheImage('tablet');

end