
function onCreate()
    precacheImage('cup/bull/Cuphead Hadoken');
	precacheImage('cup/bull/Roundabout');
	precacheImage('cup/bull/Cupheadshoot');
	precacheImage('cup/bull/GreenShit');
	precacheImage('cup/bull/NMcupheadAttacks');
	precacheImage('cup/bull/NMcupheadBull');
	precacheImage('cup/mozo');
	precacheImage('cup/gay');
	precacheImage('cup/Cardcrap');
	precacheImage('sans/heart');
	precacheImage('sans/battle');
	precacheImage('sans/waterfall');
	precacheImage('IC_Buttons');
	precacheImage('sans/Gaster_blasterss');
	precacheImage('sans/bone');
	precacheImage('sans/Cardodge');
	precacheImage('sans/DodgeMechs');
	precacheImage('healthbar-ic/bendyhealthbar - grey');
	precacheImage('healthbar-ic/bendyhealthbar');
	precacheImage('healthbar-ic/cuphealthbar');
	precacheImage('healthbar-ic/sanshealthbar');
	precacheImage('bendy/images/Damage01');
	precacheImage('bendy/images/Damage02');
	precacheImage('bendy/images/Damage03');
	precacheImage('bendy/images/Damage04');
	precacheImage('bendy/images/postdemise');
	precacheImage('bendy/images/third/Striker');
	precacheImage('bendy/images/third/Piper');
	precacheImage('bendy/images/third/StrikerDespair');
	precacheImage('bendy/images/third/PiperDespair');
	precacheImage('bendy/images/third/Ink_shit');
	precacheImage('bendy/images/third/InkRain');
	precacheImage('bendy/images/third/JzBoy');
	precacheImage('bendy/images/third/Butchergang_Bg');
	precacheImage('bendy/images/stairs/chainleft');
	precacheImage('bendy/images/stairs/chainright');
	precacheImage('bendy/images/stairs/gradient');
	precacheImage('bendy/images/stairs/scrollingBG');
	precacheImage('bendy/images/stairs/stairs');
	precacheImage('bendy/images/run/hallway');
	precacheImage('bendy/images/dark/hallway_but_Dark');
	precacheImage('bendy/images/dark/Trans');
	precacheImage('bendy/images/Cutouts/BendyCutouts');
	precacheImage('bendy/images/ready');
	precacheImage('bendy/images/set');
	precacheImage('bendy/images/go');
	precacheImage('bendy/images/BonusSongs/Curtain1 - Black _ White');
	precacheImage('bendy/images/BonusSongs/Curtain2 - Black _ White');
	precacheImage('bendy/images/BonusSongs/dabg - Black _ White');
	precacheImage('bendy/images/gay/C_00');
	precacheImage('bendy/images/gay/C_01');
	precacheImage('bendy/images/gay/C_02');
	precacheImage('bendy/images/gay/C_03');
	precacheImage('bendy/images/gay/C_04');
	precacheImage('bendy/images/gay/C_05');
	precacheImage('bendy/images/gay/C_06_BLEND_MODE_ADD');
	precacheImage('bendy/images/gay/C_07');
	precacheImage('bendy/images/gay/Particlestuff0');
	precacheImage('bendy/images/gay/Particlestuff1');
	precacheImage('bendy/images/gay/Particlestuff2');
	precacheImage('bendy/images/ForegroundEEZNUTS');
	precacheImage('bendy/images/BACKBACKgROUND');
    precacheImage('bendy/images/BackgroundwhereDEEZNUTSfitINYOmOUTH');
	precacheImage('bendy/images/MidGrounUTS');
	precacheImage("characters/bendy/BoyFriend_3rdPhase");
end