
function onCreate()
    precacheImage('bitch');
    precacheImage('queen');
    precacheImage('queen2');
    precacheImage('spam/Spam01');
	precacheImage('spam/Spam02');
	precacheImage('spam/Spam03');
	precacheImage('spam/Spam04');
	precacheImage('spam/Spam05');
	precacheImage('spam/Spam06');
	precacheImage('spam/Spam07');
	precacheImage('spam/Spam08');
	precacheImage('spam/Spam09');
	precacheImage('spam/Spam10');
	precacheImage('spam/Spam11');
	precacheImage('spam/Spam12');
	precacheImage('spam/Spam13');
	precacheImage('spam/Spam14');
	precacheImage('spam/Spam15');
	precacheImage('spam/Spam16');
	precacheImage('spam/Spam17');
	precacheImage('spam/Spam18');
	precacheImage('spam/Spam19');
	precacheImage('spam/Spam20');
	precacheImage('ribbonJumpscare');
	precacheImage('warning');
	precacheImage('heal');
	precacheImage('mikelings');
	precacheImage('ass');
	precacheImage('dark');
	precacheImage('carousel_everyman');
	precacheImage('carousel');
end